hyperparameters:
  batch_size: 100
  learning_rate: 0.0012
  epochs: 25
  input_size: 486
  output_size: 1
  hidden_size: 32
  hidden_layers: 2
  dropout_rate: 0.5
  criterion: "BCELoss"
  optimizer: "Adam"
  dependent_var: "DEP_DEL15"
  device: "cpu"
paths:
  training_data_path: 'data/processed/train_sample.csv'
  training_bucket: 'delay_mlops_data'
  input_filepath: 'data/raw/'
  output_filepath: 'data/processed/'
  inference_bucket: 'delay_mlops_inference'
  model_path: 'models/model.pth'
  model_config_path: 'src/configs/model_configs/hyperparams.json'
tuning:
  num_configs: 250
