hyperparameters:
  batch_size: 90
  learning_rate: 0.0015
  epochs: 22
  input_size: 494
  output_size: 1
  hidden_size: 32
  hidden_layers: 3
  dropout_rate: 0.5
  criterion: "BCELoss"
  optimizer: "Adam"
  dependent_var: "DEP_DEL15"
  device: "cpu"
paths:
  training_data_path: 'data/processed/train_sample.csv'
  input_filepath: 'data/raw/'
  output_filepath: 'data/processed/'
