# github workflow file that creates and uploades the monitoring container to Docker Hub
# This file is run automatically run when a commit is made to the main branch

name: "Build and push monitoring container"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build monitoring docker container and push
      uses: docker/build-push-action@v5
      with:
        file: monitoring.dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/monitoring:latest
