# github workflow file that creates and uploades the inference container to Docker Hub
# This file is run automatically run when a commit is made to the main branch


name: "Build and push inference container"

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
    - name: Build inference docker container
      run: |
        docker build -f inference.dockerfile . --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USER }}/inference
    - name: Push inference docker container to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKERHUB_USER }}/inference