# github workflow file that runs the monitoring container in google cloud compute engine
# This file is run automatically run when a new container was pushed by the other workflow

name: "Run monitoring in google cloud compute engine"

# Run when build_monitoring has run successfully
on:
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: [Build and push monitoring container]
    types:
      - completed

# Documentation for setup (easiest in google cloud shell)
# https://github.com/google-github-actions/auth#setup

jobs:
  inference:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v4'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/110692824256/locations/global/workloadIdentityPools/mlops/providers/mlops'
          service_account: 'actions-auth@wide-axiom-401015.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 416.0.0'
          project_id: 'wide-axiom-401015'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: 'Check if monitoring instance exists'
        id: 'check_if_monitoring_exists'
        run: |
          if gcloud compute instances list --filter="name=monitoring" --format="value(name)" | grep -q "inference"; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
      - name: 'If exists, update monitoring container in compute engine'
        if: steps.check_if_monitoring_exists.outputs.exists == 'true'
        run: >
          gcloud compute instances
          update-container monitoring
          --container-image docker.io/${{ secrets.DOCKERHUB_USERNAME }}/monitoring:latest
      - name: 'If not exists, run monitoring container in new compute engine'
        if: steps.check_if_monitoring_exists.outputs.exists == 'false'
        run: >
          gcloud compute instances
          create-with-container
          monitoring
          --service-account=actions-auth@wide-axiom-401015.iam.gserviceaccount.com
          --scopes=https://www.googleapis.com/auth/cloud-platform
          --container-image=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/monitoring:latest
          --zone=europe-west3-c
          --machine-type=n2d-standard-2
          --boot-disk-size=50GB
          --container-restart-policy='never'
          --tags=monitoring-server,http-server
      - name: "Delete old firewall rules"
        run: >
          gcloud compute firewall-rules
          delete allow-http-81
          --quiet
      - name: "Open port 81 in monitoring compute engine vm"
        run: >
          gcloud compute firewall-rules
          create allow-http-81
          --allow tcp:81
          --target-tags monitoring-server,http-server
          --description "Allow port 81 access to http-server"
          --direction INGRESS
          --priority 1000
          --network default
