# github workflow file that runs the tests defined in pytest in src/unit_tests
# and src/integration_tests
# This file is run automatically when a pull request is made to the main branch
# or when a commit is made to the main branch
# This file is also run when a commit is made to a pull request

name: "Run tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies without gpu support
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_tests.txt
    - name: Test with pytest
      run: |
        pytest -v
