# github workflow file that runs the tests defined in pytest in src/unit_tests
# and src/integration_tests
# This file is run automatically when a pull request is made to the main branch
# or when a commit is made to the main branch
# This file is also run when a commit is made to a pull request

name: "Run tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/110692824256/locations/global/workloadIdentityPools/mlops/providers/mlops'
        service_account: 'actions-auth@wide-axiom-401015.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 416.0.0'
        project_id: 'wide-axiom-401015'
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies without gpu support
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_tests.txt
    - name: Test with pytest
      run: |
        pytest -v
